<?php

use Dreamlands\Plate\DTemplate;
use Dreamlands\Plate\IMessageView;

/**
 * @see \Dreamlands\Action\Etc\UnicornAction::run
 * @var DTemplate $this
 * @var $title
 * @var $message
 * @var array $actions
 */
?>
<?php $this->layout('layout/full', get_defined_vars()) ?>
<h3><?= $this->e($title ?? '错的是这世界！') ?></h3>
<pre><?= $this->e($message) ?></pre>

<span class="muted">你可以…</span>
<br><br>
<ul class="pure-menu-list">
    <?php
    foreach ($actions as $idx => $action):
        $defaultClass = (isset($defaultAction) && $defaultAction === $idx) ? ' class="default"' : '';
        switch ($action[1]):
            case IMessageView::ACTION_BACK: ?>
                <li<?= $defaultClass ?>>
                    <i class="fa fa-arrow-circle-o-left"></i>
                    <a href="javascript:history.go(-1)"><?= $this->e($action[0]) ?></a>
                </li>
                <?php
                break;
            case IMessageView::ACTION_REFRESH: ?>
                <li<?= $defaultClass ?>>
                    <i class="fa fa-refresh"></i>
                    <a href="javascript:location.reload()"><?= $this->e($action[0]) ?></a>
                </li>
                <?php
                break;
            case IMessageView::ACTION_JUMP: ?>
                <li<?= $defaultClass ?>>
                    <i class="fa fa-arrow-circle-o-<?= /*黑科技，嘿嘿*/
                    false !== strpos($action[0], '回') ? 'left' : 'right'
                    ?>"></i>
                    <a href="<?= $this->e($action[2]) ?>"><?= $this->e($action[0]) ?></a>
                </li>
                <?php
                break;
        endswitch;
    endforeach;
    ?>
</ul>
<br><br>


<script>
    setTimeout(function () {
        var target = document.querySelector('.default a');
        if (target) {
            target.click();
        }
    }, 3000);
</script>
