<?php
use Dreamlands\Entity\PostEntity;
use Dreamlands\Middleware\CurrentUserMiddleware;
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var CurrentUserMiddleware $currentUser
 * @var PostEntity $board
 * @var PostEntity[] $posts
 * @var int $remain
 * @var int $from
 * @var string $next
 */
?>
<?php $this->layout('layout/default', get_defined_vars()) ?>
<h4><?= $this->e($board->title) ?></h4>

<div class="intro"><?= $this->postContent($board) ?></div>
<div class="postbox-container">
    <?php $this->insert('partial/postbox', [
        'parent' => $board
        ] + get_defined_vars()) ?>
</div>

<div class="post-list">
    <?php foreach ($posts as $post): ?>
    <div class="post">
        <?php $this->insert('partial/post', [
            'post' => $post,
            'showChildren' => true,
        ]) ?>
    </div>
    <?php endforeach ?>
</div>

<div class="more">
    <hr>
    <?php if ($remain > 0): ?>
        <a href="/b/<?= $board->id ?>?from=<?= $next ?>">更多</a>
    <?php endif ?>
    <?php if ($from > 0): ?>
        <a href="/b/<?= $board->id ?>">返回</a>
    <?php endif ?>
    <span class="muted f-right">剩余<strong><?= $remain ?></strong>条未显示</>
</div>
