<?php
use Dreamlands\Entity\PostEntity;
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var PostEntity $board
 * @var PostEntity[] $posts
 * @var int $remain
 * @var int $from
 * @var string $next
 */
?>
<?php $this->layout('layout/default', get_defined_vars()) ?>
<h5><?= $this->e($board->title) ?></h5>

<div class="intro"><?= $this->postContent($board) ?></div>
<?php $this->insert('partial/postbox', [
    'parent' => $board
]) ?>

<div class="post-list">
    <?php foreach ($posts as $post): ?>
    <div class="post">
        <?php $this->insert('partial/post', ['post' => $post]) ?>
    </div>
    <?php endforeach ?>
</div>

<div class="more">
    <hr>
    <?php if ($remain > 0): ?>
        <a href="/b/<?= $board->id ?>?from=<?= $next ?>">更多</a>
    <?php endif ?>
    <?php if ($from > 0): ?>
        <a href="/b/<?= $board->id ?>">返回</a>
    <?php endif ?>
    <span class="muted u-pull-right">剩余<strong><?= $remain ?></strong>条未显示</>
</div>
<script>
    [].forEach.call(document.querySelectorAll('.post .content'), function (el) {
        if (parseInt(el.clientHeight) < 100) return;
        el.classList.add('collapsed');
    });
</script>
