<?php
use Dreamlands\Entity\PostEntity;
use Dreamlands\Middleware\CurrentUserMiddleware;
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var CurrentUserMiddleware $currentUser
 * @var PostEntity $board
 * @var PostEntity $thread
 * @var PostEntity[] $posts
 * @var int $remain
 * @var int $from
 * @var string $next
 */
?>
<?php $this->layout('layout/default', get_defined_vars()) ?>
<div class="pure-g">
    <h4 class="pure-u-5-6 f-left">
        <?= $this->e($thread->title ?: '无标题') ?>
    </h4>
    <span class="pure-u-1-6 f-right">
        <a href="/b/<?= $board->id ?>">
            返回<?= $this->e($board->title) ?>
        </a>
    </span>
</div>

<?php if ($currentUser->getUser()) {
    $this->insert('partial/postbox', [
        'parent' => $thread
        ] + get_defined_vars());
} ?>

<div class="thread">
    <div class="post">
        <?php $this->insert('partial/post', ['post' => $thread]) ?>
    </div>
</div>


<div class="post-list">
    <?php foreach ($posts as $post): ?>
        <div class="post">
            <?php $this->insert('partial/post', ['post' => $post]) ?>
        </div>
    <?php endforeach ?>
</div>

<div class="more">
    <hr>
    <?php if ($remain > 0): ?>
        <a href="/t/<?= $thread->id ?>?from=<?= $next ?>">更多</a>
    <?php endif ?>
    <?php if (!empty($last)): ?>
        <a href="/t/<?= $thread->id ?>?from=<?= $last ?>">最新</a>
    <?php endif ?>
    <?php if ($from > 0): ?>
        <a href="/t/<?= $thread->id ?>">返回</a>
    <?php endif ?>
    <span class="muted f-right">剩余<strong><?= $remain ?></strong>条未显示</>
</div>

<style>
    .post .avatar.u_<?= sha1($thread->user->getDisplayName()) ?> {
        font-weight: bold;
    }
</style>
