<?php
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var string $pageTitle
 */
?>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="renderer" content="webkit">
<title><?= $this->e($pageTitle) ?></title>
<link rel="stylesheet" href="/assets/css/main.css">
<!--[if IE]>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<![endif]-->
<script src="/assets/js/main.js"></script>
