<?php
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var string $pageTitle
 */
?>

<title><?= $this->e($pageTitle) ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/assets/css/skeleton.min.css">
<style>
    body {
        background: hsla(210, 16%, 98%, 0.9);
    }

    a {
        text-decoration: none;
    }

    .muted {
        color: #868e96;
    }

    .postbox label {
        text-align: right;
    }

    .avatar {
        position: relative;
        display: inline-flex;
        justify-content: center;
        align-items: center;

        min-height: 56px;
        min-width: 56px;
    }

    .avatar img {
        position: absolute;
        z-index: 80;
    }

    .avatar .name {
        display: inline-block;
        position: relative;
        z-index: 100;
        background: hsla(210, 16%, 98%, 0.75);
        line-height: 56px;
        font-family: monospace;
        font-size: 14px;
    }

    .post {
        border-top: 1px solid hsla(210, 16%, 70%, 0.3);
        padding: 0 0 1em 0.5em;
    }

    .post:nth-child(2n) {
        background: hsla(210, 16%, 70%, 0.05);
    }

    .post .head {
        line-height: 28px;
        padding-bottom: 0.5em;
    }

    .post .title {
        font-weight: bold;
    }

    .post .content {
        margin: 0.25em 2em;
        overflow: hidden;
    }

    .post .content.collapsed {
        position: relative;
        max-height: 8em;
    }

    .post .content.collapsed:before {
        content: ' ';
        position: absolute;
        pointer-events: none;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        background: linear-gradient(to bottom, hsla(210, 16%, 98%, 0) 40%, hsla(210, 16%, 98%, 0.8) 80%, hsla(210, 16%, 98%, 1));
    }

    .post:nth-child(2n) .content.collapsed:before {
        background: linear-gradient(to bottom, hsla(210, 16%, 96%, 0) 40%, hsla(210, 16%, 96%, 0.8) 80%, hsla(210, 16%, 96%, 1));
    }

    .more hr {
        margin-bottom: 0.5em;
    }

    .more a {
        margin-right: 0.5em;
    }

    @media (min-width: 750px) {
        body {
            background: #e9ecef url("http://dn-mcfog-present.qbox.me/bg.jpg") top center/cover no-repeat fixed;
        }

        body > .main.container {
            box-shadow: 0 0 5px 5px hsla(210, 16%, 98%, 0.6);
            /*border: solid hsla(210, 16%, 70%, 0.8);*/
            /*border-width: 0 1em 1em 1em;*/
            border-radius: 0 0 3px 3px;

            background: hsla(210, 16%, 98%, 0.8);
        }

        .main.content {
            padding: 1em;
            background: hsla(210, 16%, 98%, 1);
        }

        .nav {
            padding: 1em;
        }
    }

    .footer {
        padding: 1em;
        opacity: 0.8;
    }

    .footer a {
        color: #222;
    }

    .footer:hover {
        opacity: 1;
        transition: 1s;
    }
</style>