<?php

use Dreamlands\Entity\PostEntity;
use Dreamlands\Middleware\CurrentUserMiddleware;
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var PostEntity $parent
 * @var CurrentUserMiddleware $currentUser
 */
?>
<form class="postbox pure-form pure-form-aligned" data-parent-id="<?= $this->e($parent->id) ?>" method="post"
      action="/post">
    <fieldset>

        <?php if (!$currentUser->getUser()): ?>
            <div class="pure-control-group j-spawn-user">
                <label for="post-sender">
                    <i class="fa fa-user-circle"></i>
                </label>
                <input type="text" id="post-sender" class="pure-input-rounded" autocomplete="off"
                       maxlength="10" placeholder="点此输入你的昵称" readonly/>

                <button class="pure-button pure-button-primary" name="signIn">
                    <i class="fa fa-sign-in"></i>
                </button>
            </div>
            <div class="pure-control-group">
                <label for="post-title">
                    <i class="fa fa-envelope-o"></i>
                </label>
                <input type="text" name="title" id="post-title" autocomplete="off" readonly/>
            </div>
            <div class="pure-control-group">
                <label for="post-content">
                    <i class="fa fa-file-text-o"></i>
                </label>
                <textarea name="content" id="post-content" cols="30" rows="10" maxlength="2048" readonly></textarea>
            </div>
            <div class="pure-control-group">
                <label>&nbsp;</label>
                <div class="pure-u">
                    <input type="submit"
                           value="<?= $parent->type === PostEntity::TYPE_BOARD ? '发布' : '回复' ?>"
                           class="pure-button pure-button-primary"
                           disabled
                    />
                </div>
            </div>
        <?php else: ?>
            <div class="pure-control-group">
                <label for="post-sender">
                    <i class="fa fa-user-circle"></i>
                </label>
                <?php $this->insert('partial/avatar', ['user' => $currentUser->getUser()]) ?>
            </div>
            <div class="pure-control-group">
                <label for="post-title">
                    <i class="fa fa-envelope-o"></i>
                </label>
                <input name="title" id="post-title" autocomplete="off" maxlength="30"/>
            </div>
            <div class="pure-control-group">
                <label for="post-content">
                    <i class="fa fa-file-text-o"></i>
                </label>
                <textarea name="content" id="post-content" cols="30" rows="10" maxlength="2048"></textarea>
            </div>
            <div class="pure-control-group">
                <label>&nbsp;</label>
                <div class="pure-u">
                    <input type="submit"
                           value="<?= $parent->type === PostEntity::TYPE_BOARD ? '发布' : '回复' ?>"
                           class="pure-button pure-button-primary"
                    />
                    <button class="pure-button button-secondary hidden" name="attachImg">贴图</button>
                </div>
            </div>

        <?php endif ?>
        <input name="parent" type="hidden" value="<?= $parent->id ?>"/>
    </fieldset>
</form>
