<?php

use Dreamlands\Entity\PostEntity;
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var PostEntity $post
 * @var PostEntity[] $postChildren
 */
?>
<div class="pure-g head">
    <div class="pure-u-7-12">
        <div class="post-no">
            <a href="javascript:void(0)"
               data-post="<?= sprintf('%08d', $post->id) ?>"
               id="post-<?= sprintf('%08d', $post->id) ?>"
               class="j-quote-post muted"
            >No. <?= sprintf('%08d', $post->id) ?></a>
            <?php if ($post->type === PostEntity::TYPE_THREAD): ?>
                <a href="/t/<?= $post->id ?>" class="thread_link">[全文]</a>
            <?php else: ?>
                <a href="/r/<?= $post->id ?>" class="muted" target="_blank">
                    <i class="fa fa-external-link"></i>
                </a>
            <?php endif ?>
        </div>
        <?= $this->postTitle($post) ?>
    </div>
    <span class="pure-u-5-12">
        <span class="f-right">
            <small class="muted">
                <?= date('Y-m-d H:i:s', $post->created_at) ?>
            </small>
            <?php $this->insert('partial/avatar', ['user' => $post->user]) ?>
        </span>
    </span>
</div>
<div class="pure-g">
    <div class="pure-u-1 content">
        <?= $this->postContent($post) ?>
    </div>
</div>

<?php if (!empty($postChildren) && $post->latest_childs): ?>
    <div class="reply-list">
        <div class="muted desc">
            共计 <?= $post->child_count ?> 条回复，<a href="/t/<?= $post->id ?>?jump=latest" class="thread_link">最新回复</a>
        </div>
        <?php
        foreach ($post->latest_childs as $id):
            $childObj = $postChildren[$id];

            ?>
            <div class="reply post">
                <?php $this->insert('partial/post', ['post' => $childObj])
                ?>
            </div>
        <?php endforeach ?>
    </div>
<?php endif ?>
