<?php

use Dreamlands\Entity\PostEntity;
use Dreamlands\Middleware\CurrentUserMiddleware;
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var CurrentUserMiddleware $currentUser
 * @var string $title
 * @var string $action
 * @var PostEntity[] $boards
 */
?>
<html lang="zh-cmn-Hans">
<head><?php $this->insert('partial/head', get_defined_vars()) ?></head>
<body id="<?= $action ?>" class="loading">
<div class="main container">
    <div class="pure-g">
        <div class="sidebar">
            <h1><a href="/" class="logo">
                <span class="fa-stack">
                  <i class="fa fa-cloud fa-stack-2x"></i>
                  <i class="fa fa-comments fa-stack-1x fa-inverse"></i>
                </span>
                </a></h1>
            <ul>
                <?php foreach ($boards as $board): ?>
                    <li>
                        <a href="/b/<?= $board->id ?>">
                            <?= $this->e($board->title) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div><!--end .nav-->
        <div class="main content">
            <?= $this->section('content') ?>
        </div><!--end .content-->
    </div>
</div><!--end .container-->
<?php $this->insert('partial/footer', get_defined_vars()) ?>
</body>
</html>
