<?php
use Dreamlands\Plate\DTemplate;

/**
 * @var DTemplate $this
 * @var string $title
 * @var string $action
 */
?>
<html lang="zh-cmn-Hans">
<head><?php $this->insert('partial/head', get_defined_vars()) ?></head>
<body id="<?= $action ?>" class="loading">
<div class="main container">
    <div class="pure-g">
        <div class="content pure-u">
            <?= $this->section('content') ?>
        </div>
    </div>
</div>
<?php $this->insert('partial/footer', get_defined_vars()) ?>
</body>
</html>
